### ISSUE TITLE
proxy not being handled correctly

### ISSUE THREAD

**Issue by rharing** [codebrewer/intellij-platform-dilbert-daily-strip-plugin#28]
in the log i see this: 6467:2019-02-12 14:02:48,453 [  22276]   WARN - .httpclient.HttpMethodDirector - Required credentials not available for BASIC <any realm>@www.dilbert.com:443
6643:2019-02-12 14:05:34,843 [ 188666]   INFO - ilbert.DilbertDailyStripPlugin - disclaimer ack'd
6644:2019-02-12 14:05:34,843 [ 188666]  ERROR - ellij.project.impl.ProjectImpl - org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripProjectComponentImpl@4c6dc44e
6648:   at org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripPluginImpl.fetchDailyStrip(DilbertDailyStripPluginImpl.java:115)
6649:   at org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripPluginImpl.fetchDailyStrip(DilbertDailyStripPluginImpl.java:108)
6650:   at org.codebrewer.intellijplatform.plugin.dilbert.strategy.CurrentDailyStripProvider.doStart(CurrentDailyStripProvider.java:129)
6651:   at org.codebrewer.intellijplatform.plugin.dilbert.strategy.AbstractDailyStripProvider.start(AbstractDailyStripProvider.java:92)
6652:   at org.codebrewer.intellijplatform.plugin.dilbert.strategy.CurrentDailyStripProvider.start(CurrentDailyStripProvider.java:56)
6653:   at org.codebrewer.intellijplatform.plugin.dilbert.ui.DailyStripPanel.initialise(DailyStripPanel.java:229)
6654:   at org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripProjectComponentImpl.projectOpened(DilbertDailyStripProjectComponentImpl.java:109)
using intellij 2017.1.6

**Comment by codebrewer** [comment]
Apologies for letting this languish for so long. Unfortunately, recent changes to the Dilbert landscape have broken the plugin and I have no interest in getting it working again. I'm archiving the project as a result.
